//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gametask_back_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class gm_usuario
    {
        public int userId { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string nome { get; set; }
        public Nullable<int> moeda { get; set; }
        public Nullable<int> nivelVida { get; set; }
        public Nullable<int> nivelExperiencia { get; set; }
    }
}
